[package]
name = "hitrace-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
ctrlc = "3.4.6"
regex = "1.11.1"
time = { version = "0.3.41", features = ["macros", "parsing"] }
which = "7.0.2"
yansi = { version = "1.0.1", features = ["detect-env", "detect-tty"] }
