[package]
name = "hitrace-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.36", features = ["derive"] }
ctrlc = "3.4.6"
regex = "1.11.1"
rust_decimal = { version = "1.37.1", features = ["serde-with-float"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
time = { version = "0.3.41", features = ["macros", "parsing", "serde"] }
which = "7.0.3"
yansi = { version = "1.0.1", features = ["detect-env", "detect-tty"] }
